name: Wordpress pipelines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:

jobs:

  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
      - name: Test
        run: |
          python manage.py migrate
          pytest

  install-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
          pip3 install flake8
      - name: Lint
        continue-on-error: true
        run: |
          flake8 .

  merge:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [ install-and-lint, install-and-test ]
    steps:
      - uses: actions/checkout@v2
      - name: Branch Merge
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'main'
          commit_message_template:  Merged {source_ref} into {target_branch}.


  build-and-push:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: merge
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CI_REGISTRY_URL }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          cache-from: ${{ secrets.CI_REGISTRY_URL }}/${{ secrets.CI_IMAGE }}:latest
          tags: |
            ${{ secrets.CI_REGISTRY_URL }}/${{ secrets.CI_IMAGE }}:${{ github.sha }}
            ${{ secrets.CI_REGISTRY_URL }}/${{ secrets.CI_IMAGE }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          wget --server-response --method POST "https://${{ secrets.PORTAINER_URL }}/api/webhooks/${{ secrets.PORTAINER_WEBHOOK_TOKEN }}"
          wget --server-response --method POST "https://${{ secrets.PORTAINER_URL }}/api/webhooks/${{ secrets.SANDBOX_PORTAINER_WEBHOOK_TOKEN }}"